<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net8.0-android</TargetFramework>
  <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
  <Nullable>enable</Nullable>
  <LangVersion>latest</LangVersion>
  <ApplicationId>com.avaloniamd2.helloworld</ApplicationId>
  <ApplicationVersion>1</ApplicationVersion>
  <ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
  <AndroidPackageFormat>apk</AndroidPackageFormat>
  <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
</PropertyGroup>

<ItemGroup>
  <ProjectReference Include="..\AvaloniaHelloWorldMD2\AvaloniaHelloWorldMD2.csproj" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="Avalonia.Android" Version="11.2.3" />
</ItemGroup>
</Project>